sonar.organization=aifred
sonar.projectKey=aifred_juice-shop
sonar.projectName=OWASP Juice Shop

# Sources
sonar.sources=lib,models,routes,views,data,frontend/src,*.ts
sonar.tests=test,frontend/src,cypress
sonar.test.inclusions=test/**/*.test.ts,frontend/src/**/*.spec.ts,cypress/**/*.ts
sonar.exclusions=node_modules/**,build/**,dist/**,frontend/dist/**,coverage/**,.nyc_output/**,i18n/**,data/static/codefixes/**,frontend/src/assets/i18n/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/server-tests/lcov.info,coverage/api-tests/lcov.info,frontend/coverage/lcov.info
sonar.coverage.exclusions=test/**,frontend/src/**/*.spec.ts,cypress/**,frontend/src/hacking-instructor/**

# Misc
sonar.sourceEncoding=UTF-8
